//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB2SDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BB2SDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit_hover {
            get {
                object obj = ResourceManager.GetObject("exit_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Configs&quot;
        ///{
        ///	&quot;Games&quot;
        ///	{
        ///		&quot;BrainBread 2&quot;
        ///		{
        ///			&quot;GameDir&quot;		&quot;%s1\hammer&quot;
        ///			&quot;Hammer&quot;
        ///			{
        ///				&quot;GameData0&quot;		&quot;%s1\bin\fgd\bb2.fgd&quot;
        ///				&quot;GameData1&quot;		&quot;%s1\bin\fgd\propper.fgd&quot;
        ///				&quot;TextureFormat&quot;		&quot;5&quot;
        ///				&quot;MapFormat&quot;		&quot;4&quot;
        ///				&quot;DefaultTextureScale&quot;		&quot;0.250000&quot;
        ///				&quot;DefaultLightmapScale&quot;		&quot;16&quot;
        ///				&quot;GameExe&quot;		&quot;%s1\hl2.exe&quot;
        ///				&quot;DefaultSolidEntity&quot;		&quot;func_detail&quot;
        ///				&quot;DefaultPointEntity&quot;		&quot;prop_static&quot;
        ///				&quot;BSP&quot;		&quot;%s1\bin\vbsp.exe&quot;
        ///				&quot;Vis&quot;		&quot;%s1\bin\vvis.exe&quot;
        ///				&quot;Light&quot;		&quot;%s1\bin\vrad.exe&quot;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameConfig {
            get {
                return ResourceManager.GetString("GameConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
